apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xg7491n1a-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xg7491n1a-python 
  name: xg7491n1a-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xg7491n1a-python 
