apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xg7491n1a-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:472f6ad0026125b86cdd2e5d2ce77bc143e59d2a@sha256:e8d332239d8f31a10e9bd9dd908e0620397953566a95ff89d05c65f7b26b403c
          name: container-image
